### ISSUE TITLE
Python 3.7.3 Compatibility

### ISSUE THREAD

**Issue by jakeee51** [MarioVilas/googlesearch#78]
Hello, I've just installed google-2.0.2 from pip. Ran the sample code and nothing printed at all. Cloned the repository from Github, tried again, and still nothing printed from the for loop again. All I want is to perform a virtual google search and return a url. The following is what happened:
```Python
>>> for url in search('"Breaking Code" WordPress blog', stop=20):
...        print(url)
...
>>>
```

**Comment by MarioVilas** [comment]
Hi!

Don't have Python 3.7.3 to try it on, but it seems to be working on 3.6.8 (the one shipped with Ubuntu):
```Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from googlesearch import search
>>> for url in search('"Breaking Code" WordPress blog', stop=20):
...   print(url)
... 
https://wordpress.org/support/topic-tag/breaking-code/
https://wordpress.org/support/topic/unintended-html-character-references-breaking-code/
https://wordpress.org/support/topic/jquery-live-is-not-a-function-2/
https://wordpress.org/support/topic/page-excerpt-does-not-show/
https://wordpress.org/support/topic/php7-compatibility-39/
https://www.blogherald.com/2007/07/16/writing-and-publishing-code-in-your-wordpress-blog-posts/
https://breakingcode.wordpress.com/page/2/
https://en.forums.wordpress.com/topic-tag/breaking-code/
https://en.forums.wordpress.com/topic/wordpress-breaking-my-embeded-html-code-why/
https://toolset.com/forums/topic/wordpress-stripping-apostrophe-and-replacing-it-with-html-breaking-code/
https://wpchase.com/free-custom-css-plugins-to-style-your-website-without-breaking-code/
https://www.namecheap.com/blog/how-wordpress-5-2-allows-non-geeks-to-fix-websites/
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mario/work/github/googlesearch/googlesearch/__init__.py", line 285, in search
    time.sleep(pause)
KeyboardInterrupt```

I would guess there's something else wrong, like bad internet connectivity for example...

**Comment by MarioVilas** [comment]
Closing due to inactivity.
